apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-deployment
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      tolerations:
      - key: "size"
        operator: "Equal"
        value: "small"
      containers:
      - name: video-editor
        image: {{ .Values.app.image }}:{{ required "app.version is required" .Values.app.version }}
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key
              key: OPENAI_API_KEY